POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "password": "1234",
    "name": "duy123",
    "phone": "01234567",
    "role": "USER",
    "email": "duy123@gmail"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "password": "1234",
    "phone": "01234567"
}
